### ISSUE TITLE
Script doesn't work with ie < 9

### ISSUE THREAD

**Issue by LoneCoder** [denivip/jquery-openxtag#1]
Ie (version 8 or less) complains that  method Object.keys is not supported.

I've rewritten the code portion to use Jquery buildin index-map function:

data.zones=Object.keys(zones).map(function(a){return a+"="+zones[a]})

data.zones=$.map(zones, function(v,i){return i+"="+v})

Thank you Nikolay for the fine plugin, now we need a patch in order to get jsonp content from openx for crossdomain use.

**Comment by kolyuchiy** [comment]
Hi! Thanks for your report. I commited the change that you suggested into repository.
Also, I fixed crossdomain issue for SPC requests.

**Comment by LoneCoder** [comment]
thx
