### ISSUE TITLE
Missing success callback call

### ISSUE THREAD

**Issue by LoneCoder** [denivip/jquery-openxtag#2]
Hi,
I think success callback is not saved in the object

$this.append(markup);
if (typeof success == 'function') {
  setTimeout(success, 0);
}

when the method looks for the function, it's is out of scope, 
so success cannot be called

**Comment by kolyuchiy** [comment]
Hi,
Thanks for the bug report. Please try the updated version.

**Comment by LoneCoder** [comment]
Hi,
thanks for the quick fix, it works well now.
May  i suggest to replace

setTimeout(success, 0);

with

setTimeout(function (){success.call($this);}, 0);

so we are able to pass the affected element to callback via this ?

bye

**Comment by kolyuchiy** [comment]
Yes, of course. It's a good suggestion.
I've updated the code.

**Comment by LoneCoder** [comment]
thank you
